### ISSUE TITLE
option -f not recognized

### ISSUE THREAD

**Issue by oleandor** [NVE/HydAPI#6]
Hi,
I get this error msg for the example below:
_option -f not recognized_

`python get-observations.py -a "INSERT_KEY_HERE" -s 12.209.0 -p 1000 -r 60 -f "2018-01-01T10:00:00" -t "2018-01-14T20:00:00"`

**Comment by havarde** [comment]
Hi,
First of all, thank you for the feedback.

I have now fixed the text so that is correct. We are only using one parameter (reference-time), so the -t will be the only parameter to use to reference time.
